# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  # - "3.3"  # not compatible with Django 1.9
  - "3.4"
  - "3.5"
  - "3.6"

# set sudo: false to use new container-based infra on travis-ci.com
sudo: false

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source django_pesapal runtests.py

# report coverage to coveralls.io
after_success: coveralls

branches:
  only:
    - master
    - develop

notifications:
    email:
        on_success: never
        on_failure: always
